[project]
name = "quest"
version = "0.1.0"
description = "Yet another CLI todo manager."
authors = [
    "Hristo Filaretov <h.filaretov@campus.tu-berlin.de>"
]
license = "MIT"
readme = "readme.md"
python = "^3.8"

[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "quest"
author = "Hristo Filaretov"
author-email = "h.filaretov@campus.tu-berlin.de"
classifiers = ["License :: OSI Approved :: MIT License"]

[tool.black]
line-length = 90
target_version = ['py38']

